### ISSUE TITLE
Ability to store connections to multiple CTP7 objects in reg_interface.py

### ISSUE THREAD

**Issue by jsturdy** [cms-gem-daq-project/xhal#2]
It would be nice to have a feature to connect multiple ```CTP7```s from within ```reg_interface.py```.
Similar to how ```AMC13Tool2.exe``` has the possibility to ```connect``` and ```select``` different cards from within the CLI

**Comment by mexanick** [comment]
The reg_interface.py is updated. In the new revision -n (--hostname) parameter is optional in case you want to run the tool in executable mode. Otherwise, upon parsing the address table a prompt will appear instantly. At this time run:
`connect _hostname_` (e.g. connect eagle34)
if no error message shown, you are connected successfully. Prompt name should change to the hostname. 
You can reconnect to another ctp7 without relaunching the tool. Simply run the connect command again. It will automatically drop the previous rpc connection and connect to a new card. In case new connection fails, you will be dropped back to initial prompt without exiting the tool. From there you can try to connect again.


Operation example:
python reg_interface.py
Parsing /home/mdalchen/work/xhal/etc/gem_amc_top.xml ...
Starting CTP7 Register Command Line Interface. Please connect to CTP7 using connect <hostname> command
CTP7 > connect eagle34
eagle34 > read GEM_AMC.OH.OH2.STATUS.FW
0x650b0000 r	GEM_AMC.OH.OH2.STATUS.FW				0x20170330
eagle34 > connect eagle63
Caught RPCErrorException: Unable to connect: No route to host
[Connection error] RPC connection failed
CTP7 > read GEM_AMC.OH.OH2.STATUS.FW
Caught NotConnectedException: Not connected to rpc service
0x650b0000 r	GEM_AMC.OH.OH2.STATUS.FW				0x00000001
CTP7 > connect eagle34
eagle34 > read GEM_AMC.OH.OH2.STATUS.FW
0x650b0000 r	GEM_AMC.OH.OH2.STATUS.FW				0x20170330
eagle34 > connect eagle64
Assertion Failed on line 52: rpc.load_module("extras", "extras v1.0.1")
[Connection error] RPC connection failed
CTP7 > connect eagle34
eagle34 > read GEM_AMC.OH.OH2.STATUS.FW
0x650b0000 r	GEM_AMC.OH.OH2.STATUS.FW				0x20170330
eagle34 > exit
